sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.2
      language: php
      env:
        - COMPOSER_OPTIONS="--prefer-lowest"
      cache:
        directories:
          - $HOME/.composer/cache/files

      before_install:
        - composer self-update

      install:
        - composer update -n "$COMPOSER_OPTIONS"

      script:
        - vendor/bin/phpunit
    - php: 7.2
      language: php
      env:
        - COMPOSER_OPTIONS="--prefer-stable"

      cache:
        directories:
          - $HOME/.composer/cache/files

      before_install:
        - composer self-update

      install:
        - composer update -n "$COMPOSER_OPTIONS"

      script:
        - vendor/bin/phpunit

    - php: nightly
      language: php
      cache:
        directories:
          - $HOME/.composer/cache/files

      before_install:
        - composer self-update

      install:
        - composer update -n "$COMPOSER_OPTIONS"

      script:
        - vendor/bin/phpunit

    - node_js: 8
      language: node_js
      cache: yarn

      install:
        - yarn

      script:
        - yarn run test:unit

  allow_failures:
    - php: nightly






