sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      language: php
      cache:
        directories:
          - $HOME/.composer/cache/files
      install: composer update

    - php: 7.2
      language: php
      env:
        - COMPOSER_OPTIONS="--prefer-lowest"
      cache:
        directories:
          - $HOME/.composer/cache/files
      install: composer update -n "$COMPOSER_OPTIONS"

    - php: 7.2
      language: php
      env:
        - COMPOSER_OPTIONS="--prefer-stable"
      cache:
        directories:
          - $HOME/.composer/cache/files
      install:
        - composer update -n "$COMPOSER_OPTIONS"

    - php: nightly
      language: php
      cache:
        directories:
          - $HOME/.composer/cache/files
      install: composer update -n "$COMPOSER_OPTIONS"

    - node_js: 8
      language: node_js
      cache: yarn
      install: yarn
      addons:
        sauce_connect: true
      script: yarn run test:sauce

  allow_failures:
    - php: nightly
